### ISSUE TITLE
Could you please share the datasets used in your paper

### ISSUE THREAD

**Issue by fhyme** [nik0spapp/sdalg#1]
Hi Nikolaos,
Thanks for your open source code of your work. Could you please share the datasets(SD Diverse and SD Non-Diverse) used in your paper? I'd like to do more research.

Best Regards,
Albert

**Comment by nik0spapp** [comment]
Hi Albert,

Thanks for your interest. I have added the datasets (diverse, non-diverse) used in the paper below:
https://github.com/nik0spapp/sdalg/tree/master/datasets

Note that the datasets contain URLs and not the actual content, so keep in mind that some of them may have been changed or deleted.

Best regards,
Nikos

**Comment by fhyme** [comment]
Hi Nikolaos,

Thank your very much. 

Best Regards,
Albert
